### ISSUE TITLE
Implement accounting rule filter editor

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#102]
The club administrator should be able to read/create/update/delete accounting rule filters. Depending on these rule filters, the FLS is able to create deliveries and therefore invoices.

For the overview the web api call api/v1/accountingrulefilters can be used.
To make CRUD operations with the AccountingRuleFilterDetails use the base web api call api/v1/accountingrulefilters/.

The details object AccountingRuleFilterDetails is used for all AccountingRuleFilterTypes, but have some properties which are related to some specific type. The following properties are used for all types:
```
Guid AccountingRuleFilterId { get; set; }
string RuleFilterName { get; set; }
string Description { get; set; }
bool IsActive { get; set; }
int SortIndicator { get; set; }
int AccountingRuleFilterTypeId { get; set; }
bool IsRuleForSelfstartedGliderFlights { get; set; }
bool IsRuleForGliderFlights { get; set; }
bool IsRuleForTowingFlights { get; set; }
bool IsRuleForMotorFlights { get; set; }
bool UseRuleForAllAircraftsExceptListed { get; set; }
List<string> MatchedAircraftImmatriculations { get; set; }
bool UseRuleForAllFlightTypesExceptListed { get; set; }
List<string> MatchedFlightTypeCodes { get; set; }
bool ExtendMatchingFlightTypeCodesToGliderAndTowFlight { get; set; }
bool UseRuleForAllStartLocationsExceptListed { get; set; }
List<string> MatchedStartLocations { get; set; }
bool UseRuleForAllLdgLocationsExceptListed { get; set; }
List<string> MatchedLdgLocations { get; set; }
bool UseRuleForAllClubMemberNumbersExceptListed { get; set; }
List<string> MatchedClubMemberNumbers { get; set; }
bool UseRuleForAllFlightCrewTypesExceptListed { get; set; }
List<int> MatchedFlightCrewTypes { get; set; }
```

The following two properties are only relevant when using AccountingRuleFilterType.RecipientAccountingRuleFilter (AccountingRuleFilterTypeId = 10):
```
public RecipientDetails RecipientTarget { get; set; }
public bool IsChargedToClubInternal { get; set; }
```
In this case (creating RecipientAccountingRuleFilter), the UI should display all persons. One person can be selected as the RecipientTarget.

The following properties are only relevant when using all other AccountingRuleFilterTypes (AircraftAccountingRuleFilter = 30):
```
public ArticleTargetDetails ArticleTarget { get; set; }
public int MinFlightTimeMatchingValue { get; set; }
public int MaxFlightTimeMatchingValue { get; set; }
public bool IncludeThresholdText { get; set; }
public string ThresholdText { get; set; }
public bool IncludeFlightTypeName { get; set; }
```

The following properties are only relevant when using all other AccountingRuleFilterTypes (NoLandingTaxAccountingRuleFilter = 20):
```
public ArticleTargetDetails ArticleTarget { get; set; }
public bool NoLandingTaxForGlider { get; set; }
public bool NoLandingTaxForTowingAircraft { get; set; }
public bool NoLandingTaxForAircraft { get; set; }
```

In this case (creating other types than RecipientAccountingRuleFilter), the UI should display all articles. One article can be selected as the ArticleTarget.

Currently the SortIndicator is not relevant. But the rule engine will consider the SortIndicator in near future and e.g. will stop rule matching process on first match.

The design proposal for the accounting rule filter editor looks like the following:
![accounting rule filter details](https://cloud.githubusercontent.com/assets/10795326/23866316/bdf0730c-0818-11e7-9208-87041870dacb.png)

**Comment by elekktrisch** [comment]
c54735951743fe5b41a09eca71033222f2c5850c 3ab8cf3d762a061a9c9da5c2a98ac58346ae0199 036e852dde329cc40a81151504b5108e4eb8ef98 efc901e9a8705ca97588ca2b9ad1ff48e04284f6 d3bdea3506cf258a2b68e4cb7019631a8318ebbe 2a1b67202a7bfe0499ea12ad75aff6b5959e8b6b be2b29876941d9cebb36b0debd99430cb5754458 6336e54ee43f5a04cfdd68503cede1d980076553
