### ISSUE TITLE
Flight date is not shown in overview for external started flights

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#11]
When saving an external started glider flight with only a landing datetime value, the overview table doesn't display a date value for this flight.

**Comment by elekktrisch** [comment]
We don't have a separate field for "flight date". It is derived from the start date/time. Change the API?

**Comment by pschuler78** [comment]
In some use cases, we only have a landing time (and a landing date). In these cases, it would be good, if we display the landing date as "flight date" in the overview. May it make sense, we add a property "FlightDate" to the FlightOverview object and the server set the correct value. Otherwise the client must decide which value should be presented.
