### ISSUE TITLE
Show IsActive property on Accounting Rule Filter Overview

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#112]
Show a column at very left side with the property/checkbox IsActive on Accounting rule filter overview page.
See also on draft:
![accounting rule filter overview](https://cloud.githubusercontent.com/assets/10795326/23821871/9d81216e-063f-11e7-878e-94635eb957ce.png)

**Comment by elekktrisch** [comment]
b5096b27e23a85318bec852c9408e1a069a5231a
