### ISSUE TITLE
LdgLocation of Towflight is set to null when editing 2nd time

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#116]
1. Create new towed glider flight with only a glider aircraft
2. save new flight (ldglocation of towflight will be removed short after save button pressed, tow flight type as do the same)
3. edit the same flight again
4. landing location is empty of the tow flight, default flight type is also no longer set

May be the problem is because the server sends some incomplete tow flight data back to client when flight details are requested for edit the flight the second time:
```
TowFlightDetailsData
:
{FlightId: "00000000-0000-0000-0000-000000000000", AircraftId: "00000000-0000-0000-0000-000000000000",…}
AirStateId
:
0
AircraftId
:
"00000000-0000-0000-0000-000000000000"
CanDeleteRecord
:
true
CanUpdateRecord
:
true
FlightDuration
:
"00:00:00"
FlightId
:
"00000000-0000-0000-0000-000000000000"
Id
:
"00000000-0000-0000-0000-000000000000"
IsSoloFlight
:
false
NoLdgTimeInformation
:
false
NoStartTimeInformation
:
false
ProcessStateId
:
0
ValidationStateId
:
0
```

**Comment by elekktrisch** [comment]
If no Tow-Aircraft is set, the whole tow flight is reset to "undefined". When attempting to save a tow-flight without an aircraft, an exception occurs: "Der Wert darf nicht NULL sein.
 Parametername: detailsRelatedAircraft"
In case this will be allowed in the future, we can just change the if-clause on line 325 in FlightsController.js

**Comment by elekktrisch** [comment]
made tow-aircraft selection required
79efba63e87064cc0b6f60150a1c6ad0281458ee

**Comment by pschuler78** [comment]
Reverted changes on client back to not require an towing aircraft when creating a new glider flight. In many cases it is not possible to know the towing flight aircraft when glider flight is prepared for start. This will be the case when multiple towing aircrafts are available.

**Comment by pschuler78** [comment]
The problem should be fixed on server-side as the server creates a tow flight record even no towing flight data will be sent by the client.

**Comment by pschuler78** [comment]
See also on server issue:  flightlog/flsweb#61

**Comment by pschuler78** [comment]
The server sends no longer towflightdetailsdata in case the glider flight has no towflight data.

The client should therefore pre-select the same landing location as the start location when the glider flight has selected a startlocation. Because when the user creates a new glider flight and selects the start location on the glider flight, the client sets start and landing location to the same also for the tow flight.

**Comment by pschuler78** [comment]
Implementing this on the server-side doesn't make sense, as then the server would maybe creates some wrong data and invalid logic for some clients - depending on client implementation.
