### ISSUE TITLE
User editor does not contains selection for role(s)

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#118]
The clubadmin user (within role ClubAdmin) is able to edit users. But in the current user editor the edited user can not be assigned to any role.

In my opinion, this functionality has already been implemented in an earlier version. Use API `api/v1/userroles` to get the list of roles.

An open question is how we handle higher roles than the current logged in user has. Means, as a club admin it must not be possible to get another user or himself higher rights than he has (like give system admin access role).

**Comment by elekktrisch** [comment]
0dc4206d90123198feac3cc351b07abe3b0a5740
