### ISSUE TITLE
Flight duration checkbox binding is wrong in accounting rule editor

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#119]
The checkbox "flight duration unlimited" must be checked/ticked to be able to enter flight duration min and max values. The value logic must be inverted to make sence.

So when checkbox is ticket, the additional fields should be hidden. When it is not ticket, the the additional fields for entering min and max values should be displayed.

**Comment by elekktrisch** [comment]
a7807a56fac340f0272ea580aadc32e250fc1274
