### ISSUE TITLE
Engine-Infos in glider editor form not shown

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#121]
Auf der Segelflug Maske habe ich leider noch einen Fehler gefunden  Browser Chrom

Beim Erfassen eine Segelflugzeugs mit Motor sind die Motoreninfos vorhanden zum erfassen.

Wenn nach dem Speichern der Flug wieder geöffnet wird fehlen die Motordaten.
Beim Kopieren eines Fluges werden die Motorzeiten auch nicht angezeigt.
Auch mit Starttyp  wechseln  z.b Flugzeugschlepp und zurück auf Eigenstart Hilft nicht. 
Ob die Motorzeiten ausgefüllt sind oder nicht hat keinen einfluss.

Workaround Segelflugzeug wechseln dann zurück auf ein Segelflugzeug mit Motor danach sind die Motorstunden Felder vorhanden.

**Comment by elekktrisch** [comment]
32250986fdddf4d2b48489b5edc0e3cf7f57e7ad
