### ISSUE TITLE
Motor flight overview shows UTC start and landing time instead local time

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#126]
The motor flight overview table shows the start and landing time in UTC instead of local time. When editing the flight the motor flight editor form shows the correct local time for start and landing.

The glider flight overview is correct.

**Comment by elekktrisch** [comment]
time format on the wire seems to be UTC but missing time-zone information

**Comment by pschuler78** [comment]
Fixed on server side as time loaded from database was not initialized with UTC format.
