### ISSUE TITLE
implement rule tests

### ISSUE THREAD

**Issue by elekktrisch** [flightlog/flsweb#129]
[AccountingRuleTest-Form-Design.pdf](https://github.com/flightlog/flsweb/files/1019896/AccountingRuleTest-Form-Design.pdf)

**Comment by pschuler78** [comment]
Paged Test-Overview: GET api/v1/deliverycreationtests/page/{pageStart:int?}/{pageSize:int?} returns PagedList<DeliveryCreationTestOverview>
DeliveryCreationTestDetails GET api/v1/deliverycreationtests/{deliveryCreationTestId} returns DeliveryCreationTestDetails

**Comment by pschuler78** [comment]
For run a test delivery use: GET api/v1/deliverycreationtests/testdeliveryforflight/{flightId}

**Comment by pschuler78** [comment]
implemented so far
