### ISSUE TITLE
Masterdata are still available after new login with other club user

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#141]
The master data like flight types must not be available when logout and login with other club user.

Currently, when first login with a user of club A, the master data are loaded from club A. When logout and login again with a user of club B, the master data are available from the club A (wrong club).

**Comment by elekktrisch** [comment]
changed login/logout methods to delete cache. please double-check if this was the cause.

**Comment by pschuler78** [comment]
Fixed during last few releases, latest on 1.10.0
