### ISSUE TITLE
Flight can be editet after deliveri to PROFFIX

### ISSUE THREAD

**Issue by arminstutz** [flightlog/flsweb#166]
Flight ID 893b7de4-3288-40c6-8cd4-1c894d24070e chaged from 09 to 15 Min tow time
entry to Fligth ID via Report (last 30 Days)
drill down to Flight
change tow time 
click (Bemerkung)
then Save (Speichern)

New TowTime will be saved

Done in Test system
[FLS_09.pdf](https://github.com/flightlog/flsweb/files/1863002/FLS_09.pdf)

**Comment by pschuler78** [comment]
Flight is not in process state "DeliveryBooked", it is in "DeliveryPrepared" state. In this state, the club admin is able to edit the flight until the Proffix interface catches the delivery AND set it as processed.
