### ISSUE TITLE
Deliveri Item rule will not work

### ISSUE THREAD

**Issue by arminstutz** [flightlog/flsweb#167]
Landings of Externel Sailplain in Buochs with filter "Landetaxen Externes Segelflugzeug" will not work.

[FLS_10.docx](https://github.com/flightlog/flsweb/files/1862986/FLS_10.docx)

**Comment by pschuler78** [comment]
Landing tax didn't consider flights which has no flight time information (checkbox set for NoStartTimeInformation or NoLdgTimeInformation).
No, the landing tax rule consider these flags and set the rule condition according it.
