### ISSUE TITLE
Flight instructor license date is not set correctly

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#22]
When trying to select the flight instructor license end date by the calender control (e.g. 30.09.2018) and save the profile data. The license expire date is set then to one day before (e.g. 29.9.2018). When navigating back to the profile, the calender control has still selected the same date, but the field shows the date minus 1 day.

**Comment by pschuler78** [comment]
The issue is still available. When selecting a date (e.g. 30.09.2018) in the flight instructor license end date, the client set the property to 2018-09-29T22:00:00Z. The server stores this value 1-to-1. When the client displays the dashboard, the same server value 2018-09-29T22:00:00Z is sent back to client and the client shows the date "29.09.2018" instead 30.09.2018.
The client should set the property to "2018-09-30T00:00:00Z" (in this example).

**Comment by elekktrisch** [comment]
oops, overlooked one of the date fields.
