### ISSUE TITLE
Add filter to person overview list

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#32]
Add ability to filter person overview list based on license information like:
HasGliderInstructorLicence (Glider instructor)
HasGliderPilotLicence (Glider pilot)
HasGliderTraineeLicence (Glider trainee)
HasMotorPilotLicence (Motor flight pilot)
HasTowPilotLicence (Tow pilot)

**Comment by elekktrisch** [comment]
fba2829600292b100637196c9051891c56637698
