### ISSUE TITLE
Add filter to user overview list

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#34]
Add ability to filter user overview list based on account status information like:
AccountStateId (active, inactive users)

**Comment by elekktrisch** [comment]
105012815edf348600d30e3b3e8dd850d40b328f

**Comment by pschuler78** [comment]
User overview list does not display users, even the server sends user data. Filter seems to be implemented incorrect.

**Comment by elekktrisch** [comment]
filter stopped working since we changed the content of AccountState from the id to the name. Adjusted in the filter: f5db292ca71a6aed0fb75a17020d5fde6392df38
