### ISSUE TITLE
Add glider license state information to dashboard

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#41]
Add glider license state information to dashboard.
- mark section in red when LicenceStateKey = "NotOK"
- mark section in yellow when LicenceStateKey = "Warning"
- mark section in green when LicenceStateKey = "OK"

Add flight statistics with required values, current flown values and difference

**Comment by elekktrisch** [comment]
afc6e78f7c0788f36d52003fca9929a2b5f10ac5
