### ISSUE TITLE
IsSoloFlight checkbox is not set correctly after loading and editing a flight

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#42]
Reproduceable steps
1. Create new gliderflight
2. Select double seat glider (HB-3407)
3. Select pilot
4. Select charter flight type (60)
5. Tick Checkbox "IsSoloFlight"
6. Select start and landing information
7. Add towing flight information
8. Save flight

The clients sets the IsSoloFlight = true. The server saves the information correct and sends the flight back with IsSoloFlight = true.

When after saving the flight, the flight is loaded and edited again, the form doesn't activate/tick the IsSoloFlight checkbox.

**Comment by elekktrisch** [comment]
e2188805582d5929bc2451d3c001ceabe10b5fcb
