### ISSUE TITLE
Birthday values are set incorrect

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#44]
1. Edit a person (without a defined birthday date)
2. Select a birthday date (e.g. 1.5.2016)
3. Save the person record
4. The client sends a birthday date value of "2016-04-30T00:00:00Z" instead of "2016-05-01T00:00:00Z"

When now the steps 1-3 are done again, the client sends the correct birthday value then.

When trying to deleted the birthday value, the client sends not a null value, instead the client sends a date before the last saved date.

**Comment by elekktrisch** [comment]
3992c8f7a5c064976ef01b5e49530fdd357e2ef6
