### ISSUE TITLE
Flights in previous years are shown in current year on dashboard graph

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#45]
The flight statistic graph on dashboard shows 12 months in x-axis instead 24 months. Flights in the previous year (e.g. 2015) are shown in the same month in 2016. See printscreen:

![dashboard](https://cloud.githubusercontent.com/assets/10795326/15481000/a9b36f98-2128-11e6-88b7-c87220d5a595.jpg)
![flights](https://cloud.githubusercontent.com/assets/10795326/15481002/acfdba82-2128-11e6-9a6c-d4f97ee90646.jpg)

**Comment by elekktrisch** [comment]
changed as discussed, by adding previous and current year:
d6a30c14bb8a73264f6eb104ddc5998809e4bd22
