### ISSUE TITLE
aircraft reservation overview shows UTC times

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#51]
The overview page of aircraft reservation shows the reservation time as UTC instead in localtime. The server sends the UTC time, but without the "Z" at the end of the JSON time string.

**Comment by elekktrisch** [comment]
Also, the reservation time entered manually is sent as UTC to the server without being converted.

**Comment by elekktrisch** [comment]
30b3a6fa00d246e8e333385fc457e74fb30894cd
