### ISSUE TITLE
Reservation time is displayed in UTC on planning day details

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#56]
When a aircraft reservation has a specific time period (not whole day), the UTC time is displayed on the planning day section (planning day details).

**Comment by elekktrisch** [comment]
duplicate of https://github.com/flightlog/flsweb/issues/51 ?

**Comment by pschuler78** [comment]
#51 is related to the reservation section only. #56 is for the planning day section.

steps to reproduce:
1. create a planning day
2. create an aircraft reservation on this planning day with a specific time
3. see the planning day which shows now the aircraft reservation below, but with the UTC time.

**Comment by elekktrisch** [comment]
hardcoded to utc, even though still not sure if this is a good idea.
0741e5985066a90328ea1519330daf2b6c79981d
