### ISSUE TITLE
Coupon number is sent to server even it is not displayed

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#58]
After creating a flight with a required coupon number (passenger flights), the client sends the next created flights with the same coupon number, even the client does not display the coupon number field. The client must send the flight data without a coupon number.

**Comment by pschuler78** [comment]
The coupon number is only sent by client, when a flight copy was done, but the flight type was changed. It should also be fixed on server side (reported as flightlog/flsserver#33)

**Comment by elekktrisch** [comment]
91d83f697a690ab4232ad55de1b89e4517e6621b
