### ISSUE TITLE
Safety status does not match

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#78]
It seems that the safety status does not match between the graphical version and the text description. The graphic version shows green, but the text is still yellow.

The [http://www.trainingsbarometer.de](http://www.trainingsbarometer.de/) shows for 18 Starts and 26 h flight time the yellow status.

FLS shows the following screen:
![dashboard](https://cloud.githubusercontent.com/assets/10795326/17455940/d2d7e064-5bc7-11e6-8355-aec5c6cda232.jpg)

**Comment by elekktrisch** [comment]
it is a gradient and thus there is no hard limit between yellow and green. however, we can raise the percentage for which it starts migrating from yellow to green.
