### ISSUE TITLE
Input format of engine counter values in flight editor forms depending on aircraft counter unit type

### ISSUE THREAD

**Issue by pschuler78** [flightlog/flsweb#82]
The input format of engine counter values in flight editor forms must be depending on the aircraft counter unit type values.

May use the following formats:
1. For "min" (Minutes) use format: "hhhh:mm"
2. For "100min" (100 minutes per hour) use format: "hhhh.mm"
3. For "sec" (Seconds) use format: "hhhh:mm:ss"
4. For "6sec" (1/10 minutes) use format: "hhhh:mm.ss"

**Comment by elekktrisch** [comment]
implemented directive capable of formatting for "Min" and decimal

**Comment by pschuler78** [comment]
Format is updated correctly when loading the previously saved flight. But the calculated times are not correct. Saved 100.92, but get displayed 100.91. The same on both counter fields. It looks like there is one second or something like this lost and therefore calculated wrong.

**Comment by pschuler78** [comment]
100.90 or 100.75 will be calculated correctly. So it seems only for some special values.

**Comment by pschuler78** [comment]
Works as expected. Issue can be closed.
