### ISSUE TITLE
Can not save Flight with Instructor 

### ISSUE THREAD

**Issue by arminstutz** [flightlog/flsweb#95]
Error Message
Failed to insert flight

An error occurred while updating the entries. See the inner exception for details.

![erroe_on save](https://cloud.githubusercontent.com/assets/19899476/19411589/ec356e72-9304-11e6-9e0c-ccc69b9c8926.png)

**Comment by pschuler78** [comment]
Fixed issue.
Missing FlightCrewType record in database for "observer" flight crew type.
