### ISSUE TITLE
Fluglehrer bei Motorflugerfassung

### ISSUE THREAD

**Issue by arminstutz** [flightlog/flsweb#97]
Bei Motorflug mit Flugtyp Schulung ist kein Feld für den Fluglehrer / Überwacher vorhaqnden.

Vermutlich neue Funktion Fluglehrer / Überwachungspilot in Motorflugmaske  nicht angepasst.

**Comment by elekktrisch** [comment]
41904a8b4189c370d9b5ff39ecc3b19c8fea5268
