### ISSUE TITLE
Inbound and Outbound on Powerplain /  TMG entering

### ISSUE THREAD

**Issue by arminstutz** [flightlog/flsweb#99]
If I create a new Motor-Aircraft / TMG Flight with Takeoff Buochs ( Inbound Outbound rule aply) the Inbound and Outbound fields only show up on edit .

on initial entering Buochs
![image](https://cloud.githubusercontent.com/assets/19899476/21580931/55039a40-d019-11e6-9b66-33d0b4772297.png)

on second open same Flight (example)
![image](https://cloud.githubusercontent.com/assets/19899476/21580932/6f3517a4-d019-11e6-9913-3f84f58c0f5f.png)

**Comment by elekktrisch** [comment]
41904a8b4189c370d9b5ff39ecc3b19c8fea5268
